-- Вариант 1. Использование LIMIT/OFFSET
SELECT DISTINCT NE_LE
FROM PATIENTS
ORDER BY NE_LE DESC
LIMIT 1 OFFSET 1;

-- Вариант 2. Использование подзапрос
SELECT MAX(NE_LE)
FROM PATIENTS
WHERE NE_LE < (SELECT MAX(NE_LE) FROM PATIENTS);