SELECT md.MEDECINS_ID, 
	md.NOM || ' ' ||  md.PRENOM AS "ФИО врача",
	ROUND(SUM(pl.DUREE) * 1.0 / 60, 2) as "Общая длительность приема в часах",
    COUNT(DISTINCT pl.PATIENTS_ID) AS "Количество уникальных пациентов"
FROM PLANNING pl
JOIN MEDECINS md
ON pl.MEDECINS_ID = md.MEDECINS_ID
WHERE EXTRACT(MONTH FROM pl.HEURE) = EXTRACT(MONTH FROM CURRENT_DATE)
AND EXTRACT(YEAR FROM pl.HEURE) = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY md.MEDECINS_ID, md.NOM, md.PRENOM;